name: highway_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flit-core=3.8.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - sympy=1.11.1
  - tk=8.6.12
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - typing_extensions=4.4.0
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.4
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.0
      - cloudpickle==2.2.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - decorator==4.4.2
      - docopt==0.6.2
      - farama-notifications==0.0.4
      - fonttools==4.39.3
      - google-auth==2.17.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.53.0
      - gymnasium==0.28.1
      - highway-env==1.8.1
      - imageio==2.27.0
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - jax-jumpy==1.0.0
      - kiwisolver==1.4.4
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - moviepy==1.0.3
      - oauthlib==3.2.2
      - packaging==23.0
      - pandas==2.0.0
      - proglog==0.1.10
      - protobuf==4.22.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.3.0
      - pygments==2.14.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests-oauthlib==1.3.1
      - rich==13.3.3
      - rsa==4.9
      - scikit-image==0.20.0
      - scipy==1.10.1
      - stable-baselines3==2.0.0a2
      - tensorboard==2.12.1
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tqdm==4.65.0
      - tzdata==2023.3
      - werkzeug==2.2.3
      - zipp==3.15.0
